on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: codeberg-tiny-lazy
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
      - run: npm ci
      - run: npx tsc --project .
      - run: npx tsc --project ./tsconfig.pack.json
      - run: npx eslint .
      - run: npx prettier --check .
      - run: npm audit
      - run: npm outdated
