name: Release

on:
  push:
    tags: v*

jobs:
  build:
    # Run build on main as well to make sure it's working before we make a release
    runs-on: ubuntu-latest
    container:
      # Fedora 42 ships GNOME 48, i.e. the version we currently support
      image: docker.io/fedora:42
    steps:
      - name: Install git, and gnome-shell
        run: dnf install -y --setopt=install_weak_deps=False add-determinism git gnome-shell
      - uses: actions/checkout@v4
      - run: gnome-extensions pack
      # Make artifact reproducible
      - run: SOURCE_DATE_EPOCH=0 add-determinism xwayland-indicator@swsnr.de.shell-extension.zip
      - uses: actions/upload-artifact@v4
        with:
          path: xwayland-indicator@swsnr.de.shell-extension.zip

  attest:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: xwayland-indicator@swsnr.de.shell-extension.zip

  create-release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          # This makes sure we actually get the tag message body down below,
          # see https://github.com/actions/runner/issues/712
          ref: "${{ github.ref }}"
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - run: echo "RELEASE_SUBJECT=$(git tag -ln1 --format='%(contents:subject)' "${GITHUB_REF_NAME}")" >> "$GITHUB_ENV"
      - run: git tag -ln1 --format='%(contents:body)' "${GITHUB_REF_NAME}" > ${{ github.workspace }}-body.txt
      - uses: softprops/action-gh-release@v2
        with:
          name: "${{ env.RELEASE_SUBJECT }}"
          body_path: "${{ github.workspace }}-body.txt"
          files: "xwayland-indicator@swsnr.de.shell-extension.zip"
          fail_on_unmatched_files: true
